SG_THEME = 'DarkGrey6'
LIGHT_SG_THEME = 'LightGray'
KEY_FILE = 'config.bin'
SALT_FILE = 'sconfig.bin'
UI_SETTINGS_FILE = 'gpt-to-ffmpeg.json'
PROMPT_HISTORY_FILE = 'prompt-history.log'
FFMPEG_HISTORY_FILE = 'cmd-history.log'
OPENAI_API_SITE = 'https://beta.openai.com/account/api-keys'
